version: '3'
services:
  postgres:
    build:
      /postgres
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ../.env
  app:
    build:
      /app
    ports:
      - "8080:8080"
    env_file:
      - ../.env

volumes:
  db:
